### ISSUE TITLE
Create Header

### ISSUE THREAD

**Issue by CharlyJazz** [MeteoriteNetwork/MuyUtil-WP-Theme#2]
![image](https://user-images.githubusercontent.com/12489333/37673258-23537b5c-2c46-11e8-8b1f-edf99a017be8.png)

- [ ] Desktop

- [ ]  Tablet

- [ ] Mobile with this [library](https://github.com/mblode/burger)

**Comment by extrasad** [comment]
I will work on this issue @CharlyJazz @abdiangel
