### ISSUE TITLE
Create Footer

### ISSUE THREAD

**Issue by CharlyJazz** [MeteoriteNetwork/MuyUtil-WP-Theme#3]
![image](https://user-images.githubusercontent.com/12489333/37673476-ae7e8302-2c46-11e8-8f39-816ff6937702.png)

- [ ] Desktop

- [ ]  Tablet

- [ ] Mobile with this [library](https://github.com/mblode/burger)

**Comment by JoshieS** [comment]
Taking care of this. @abdiangel @extrasad @CharlyJazz

**Comment by CharlyJazz** [comment]
Perfect, create a new folder named 'components' and create a new html file
named 'footer'

2018-03-21 14:21 GMT-04:00 Joseph Suarez <notifications@github.com>:

**Comment by CharlyJazz** [comment]
@abdiangel  Take this
