### ISSUE TITLE
Create Partner

### ISSUE THREAD

**Issue by CharlyJazz** [MeteoriteNetwork/MuyUtil-WP-Theme#4]
![image](https://user-images.githubusercontent.com/12489333/37673523-cec6f536-2c46-11e8-87e8-06325d805ebb.png)

- [ ] Desktop
- [ ] Tablet
- [ ] Mobile

**Comment by abdiangel** [comment]
I will work on this issue @CharlyJazz  @extrasad

**Comment by abdiangel** [comment]
This is how it looks 
![screenshot-2018-3-22 document](https://user-images.githubusercontent.com/27755414/37792625-9f252abc-2de2-11e8-8251-3ba1c65709f0.png)
