### ISSUE TITLE
Create "Quienes Somos" Page

### ISSUE THREAD

**Issue by CharlyJazz** [MeteoriteNetwork/MuyUtil-WP-Theme#5]
![image](https://user-images.githubusercontent.com/12489333/37673638-1b27745a-2c47-11e8-90f1-0b31c5e4c191.png)

- [ ] Desktop
- [ ] Tablet
- [ ] Mobile

**Comment by abdiangel** [comment]
I will take care of this @extrasad @CharlyJazz
