### ISSUE TITLE
Create "Inicio" Page

### ISSUE THREAD

**Issue by CharlyJazz** [MeteoriteNetwork/MuyUtil-WP-Theme#6]
![image](https://user-images.githubusercontent.com/12489333/37673675-3c32b63c-2c47-11e8-8d91-5386ab11b027.png)

- [ ] Desktop
- [ ] Tablet
- [ ] Mobile

**Comment by abdiangel** [comment]
I will take care of this @extrasad @CharlyJazz @JoshieS
