### ISSUE TITLE
Create "Productos" Page

### ISSUE THREAD

**Issue by CharlyJazz** [MeteoriteNetwork/MuyUtil-WP-Theme#7]
![image](https://user-images.githubusercontent.com/12489333/37673709-566a39ee-2c47-11e8-8ff0-b94534a6a73b.png)

- [ ] Desktop
- [x] Tablet
- [ ] Mobile

**Comment by extrasad** [comment]
I will take care of this @abdiangel @CharlyJazz @JoshieS
