### ISSUE TITLE
Create "Contacto" Page

### ISSUE THREAD

**Issue by CharlyJazz** [MeteoriteNetwork/MuyUtil-WP-Theme#8]
![image](https://user-images.githubusercontent.com/12489333/37673775-78799098-2c47-11e8-8cd3-f6c4c0f6b0ff.png)
- [ ] Desktop
- [ ] Tablet
- [ ] Mobile

**Comment by abdiangel** [comment]
I will take care of this @extrasad @CharlyJazz
